### ISSUE TITLE
Hint for documentation prior to installation

### ISSUE THREAD

**Issue by one7two99** [elliotkillick/qvm-create-windows-qube#14]
The documentation should include an information that the script will install packages in the fedora-30 template.
I like to keep my default qubes template as they are and use them as "baseline" templates for other templates to which I install template specific packages.
As far as I can see it will only install one package datefudge into the fedora-30 template and as such the process is reversible.
Otherwise great work!

**Comment by heinrich-ulbricht** [comment]
I was surprised by this as well and interrupted the script immediately to check if this is intended. It is. Also very telling how good my code review of the script had been before running it...

**Comment by elliotkillick** [comment]
Good point. I've documented modification of the global default template in the installation instructions (https://github.com/elliotkillick/qvm-create-windows-qube/commit/a11178268d56716a116653923c5d730f07fe9507). I would add an option to customize it with the `install.sh` command-line arguments too but there's not much point because I plan to replace it with proper packaging anyway.
