### ISSUE TITLE
Alternate qubes-windows-tools available

### ISSUE THREAD

**Issue by brendanhoar** [elliotkillick/qvm-create-windows-qube#15]
https://github.com/tabit-pro/qwt-crossbuild/

This may help address the win10/windows server issues w/r/t volume setup necessary to support templates.

**Comment by elliotkillick** [comment]
Hi Brendan,

I believe you're referring specifically to this file here: https://github.com/tabit-pro/qwt-crossbuild/blob/master/diskpart.ps1

It may indeed be possible for us to patch the private volume setup issue locally in this project. However, it isn't my goal to make this project a bunch of dodgy fixes for QWT when what should really be happening is those issues being addressed upstream.

This issue in particular may have already been patched upstream, see here:
https://github.com/elliotkillick/qvm-create-windows-qube/issues/13

Though, as I'm sure you are well aware of by now, QWT lacks an active maintainer and so that patch, while merged, hasn't been applied to a new version of the installer. :/

**Comment by elliotkillick** [comment]
Please feel free to fork if you would like to implement these upstream fixes locally in your own repo. However, I will not be maintaining them myself.

**Comment by brendanhoar** [comment]
> Please feel free to fork if you would like to implement these upstream fixes locally in your own repo. However, I will not be maintaining them myself.

Understood. I'll do so. :)

Thanks for all the work so far.

B
