### ISSUE TITLE
Selection of storage pool

### ISSUE THREAD

**Issue by Ashaman-** [elliotkillick/qvm-create-windows-qube#21]
It would be really nice if it were possible to select the storage pool to use for the Windows installation. Cloning to shift pools after installation is really cumbersome.

**Comment by elliotkillick** [comment]
As in an LVM storage pool on another disk, right?

I didn't know this was possible until now but it turns out it is:
https://www.qubes-os.org/doc/secondary-storage/

This looks like a pretty easy feature to add just using the `-P` option of `qvm-create` as it says in the above documentation . (Once the user already created the LVM pool themselves)

**Comment by cbmiller2610** [comment]
Just as a note: I have done what Elliot suggested above, I simply changed the qvm-create command within qvm-create-windows-qube.sh to add the -P option.  Worked like a charm.

**Comment by elliotkillick** [comment]
Good news, I added this feature in https://github.com/elliotkillick/qvm-create-windows-qube/commit/b5089a3c66f914de7f760f123731f6e01b1e0d95!
