### ISSUE TITLE
Windows 10 LTSC is broken

### ISSUE THREAD

**Issue by bowtiediguana** [elliotkillick/qvm-create-windows-qube#37]
Known issue: https://social.technet.microsoft.com/Forums/en-US/87b81fa7-f1d8-412f-91ac-e53c0a2578f3/windows-10-enterprise-ltsc-evaluation-dead-on-arrival-quotproduct-key-is-blockedquot?forum=win10itprosetup

#upstream #wontfix

**Comment by elliotkillick** [comment]
I noticed you tagged this #wontfix, however, at the bottom of that link it looks like someone with an inside connection to Microsoft was able to confirm successful repro with the people who work at Microsoft. Is it possible that this issue will just be fixed in the next LTSC release then?

You can always use Window Server as as substitute as it also runs on the LTSC update track.
