### ISSUE TITLE
install.sh fails: No match for argument: qubes-windows-tools

### ISSUE THREAD

**Issue by klausagnoletti** [elliotkillick/qvm-create-windows-qube#50]
After following the install instructions I get this error. No idea why. Can you help?

[klaus@dom0 ~]$ ./install.sh 
[i] Installing Qubes Windows Tools...
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
Qubes OS Repository for Dom0                    2.9 MB/s | 3.0 kB     00:00    
No match for argument: qubes-windows-tools
Error: Unable to find a match: qubes-windows-tools
[!] Error installing Qubes Windows Tools! Exiting...
[klaus@dom0 ~]$ ./install.sh 
[i] Installing Qubes Windows Tools...
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
Qubes OS Repository for Dom0                    2.9 MB/s | 3.0 kB     00:00    
No match for argument: qubes-windows-tools
Error: Unable to find a match: qubes-windows-tools
[!] Error installing Qubes Windows Tools! Exiting...

**Comment by GovtIssueJoe** [comment]
Also seeing this issue on a fresh install of R4.1rc2.

It is also attempting to use the Fedora 32 template, rather than the installed Fedora 34 template.

Dom0:
$./install.sh
Installing Qubes Windows Tools...
Using sys-firewall as UpdateVM to download updates for Dom0; this make take some time...

sys-firewall:
warning: Converting database from bdb_ro to sqlite backend
Fedora 32 - x86_64
Fedora 32 - x86_64 - Updates
Qubes Dom0 Repository (updates)
Qubes Templates repository
No match for argument: qubes-windows-tools
Error: Unable to find a match: qubes-windows-tools
Fetching updates failed with code 1; press Enter to exit

Dom0:
Qubes OS Repository for Dom0
No match for argument: qubes-windows-tools
Error: Unable to find a match: qubes-windows-tools
[!] Error installing Qubes Windows Tools! Exiting...

**Comment by wiktorcie** [comment]
Same issue. Looks like qubes-windows-tools is not available for 4.1 yet. Will try to build manually and report back soon. Link for reference -> https://github.com/tabit-pro/qubes-windows-tools-cross

**Comment by PeterWq** [comment]
same issue.
any solution available?

**Comment by wiktorcie** [comment]
bump, any workarounds?

**Comment by petaramesh** [comment]
Get the latest QWT from here : https://github.com/tabit-pro/qubes-windows-tools-cross/releases
Manually copy the rpm to dom0 and install it, you're done !

**Comment by telepath** [comment]
This works, but the package seems to be incomplete, it's missing the "move user profiles" package. With the iso from this image, that part is disabled by default and leads to a "please insert disk" issue when its enabled.

So the question where to find a working version of qubes-windows-tools remains.

**Comment by telepath** [comment]
I built the current version of the package from https://github.com/tabit-pro/qubes-windows-tools-cross, and that one seems to work perfectly (only tested windows 7 for now).
So, let's hope there will be a new release there soon, and maybe integration into qubes repositories.

**Comment by daktak** [comment]
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing qubes-windows-tools

**Comment by elliotkillick** [comment]
Qubes OS R4.1 does appear to have Qubes Windows Tools now: https://qubes-mirror.igniterefereeing.com.au/repo/yum/r4.1/current/dom0/fc32/rpm/

This is one of the Qubes OS mirrors. Doing a simple CTRL + F for "qubes-windows-tools" yields results.
