### ISSUE TITLE
qvm-create-windows-qube.sh does not appear

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [elliotkillick/qvm-create-windows-qube#6]
Hi,

I followed the instructions in the README, but at the end of running install.sh there was no 'qvm-create-windows-qube.sh' for me to run.  The windows-mgmt qube was installed (though I'm still a bit unclear on its purpose, I did notice that you said it was used for creating Windows qubes).

**Comment by elliotkillick** [comment]
I just tested the `install.sh` script and sure enough after everything was said and done a `qvm-create-windows-qube.sh` was placed in the current directory of Dom0.

Please inform me what template `windows-mgmt` is being based off of and provide me the output of your `install.sh`.

Attached is an example output of the one I just did. (I tested with `windows-mgmt-2 ` because I already had a `windows-mgmt` but yours should say `windows-mgmt`)

The purpose of `windows-mgmt` is the same as any other qube in Qubes. It's to do security by isolation/compartmentalization (i.e. the security model Qubes is based off of). This ensures that, for example, a malicious Windows ISO won't result in the compromise of `Dom0`. Additionally, my code may have a bug in it or even I myself may be malicious and in that case it would be far better to just have `windows-mgmt` compromised rather than `Dom0`. You will notice Qubes OS does a similar thing with the `default-mgmt-dvm` which exists in my list of qubes. It's all about minimizing the attack surface of `Dom0`.

```
[i] Creating windows-mgmt-2...
[i] Increasing storage capacity of windows-mgmt-2...
[i] Installing package dependencies on fedora-30...
Fedora Modular 30 - x86_64                            XX
Fedora Modular 30 - x86_64 - Updates           XX
Fedora Modular 30 - x86_64 - Updates           XX
Fedora 30 - x86_64 - Updates                         XX
Fedora 30 - x86_64 - Updates                         XX
Fedora 30 - x86_64                                         XX
Qubes OS Repository for VM (updates)          XX
Qubes OS Repository for VM (updates)          XX
Package genisoimage-1.1.11-41.fc30.x86_64 is already installed.
Package geteltorito-0.6-9.fc30.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[i] Shutting down fedora-30...
[i] Cloning qvm-create-windows-qube GitHub repository...
Cloning into 'qvm-create-windows-qube'...
[i] Please check for a good PGP signature (Verify it out-of-band if necessary)...
gpg: Signature made Sat Nov 30 07:48:44 2019 UTC
gpg:                using EDDSA key 018FB9DE6DFA13FB18FB5552F9B90D44F83DD5F2
gpg: Good signature from "Elliot Killick <elliotkillick@zohomail.eu>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 018F B9DE 6DFA 13FB 18FB  5552 F9B9 0D44 F83D D5F2
[i] Downloading Windows 7 (Other versions of Windows can be downloaded later by using download-windows.sh)...
[i] Downloading Windows media from Microsoft servers...
[i] Downloading Windows 7...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5604M  100 5604M    XX
[i] Verifying integrity...
win7x64-ultimate.iso: OK
[+] Successfully downloaded and verified integrity of Windows media!
[i] Shutting down windows-mgmt-2...
[i] Air gapping windows-mgmt-2...
[i] Installing Qubes Windows Tools...
updates/metalink                         XX    
--> Running transaction check
---> Package qubes-windows-tools.noarch 0:4.0.1-3 will be reinstalled
--> Finished Dependency Resolution
qubes-windows-tools-4.0.1-3.noarch.rpm            XX 
find: '/var/lib/qubes/dom0-updates/var/cache': No such file or directory
Qubes OS Repository for Dom0                                                                                                                         XX
Package qubes-windows-tools-4.0.1-3.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[i] Copying qvm-create-windows-qube.sh to Dom0...
[+] Installation complete!
```

**Comment by e6lk7dqzm83p** [comment]
Hi,

'windows-mgmt' is based off of a fedora-30 template.

I deleted the 'windows-mgmt' qube that was previously created and got this output:
$ chmod +x install.sh && ./install.sh
[i] Creating windows-mgmt...
[i] Increasing storage capacity of windows-mgmt...
[i] Installing package dependencies on fedora-30...
Last metadata expiration check: 0:06:30 ago on Tue Jan 28 23:52:41 2020.
Package genisoimage-1.1.11-40.fc29.x86_64 is already installed.
Package geteltorito-0.6-8.fc29.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[i] Shutting down fedora-30...
[i] Cloning qvm-create-windows-qube GitHub repository...
Cloning into 'qvm-create-windows-qube'...
[i] Please check for a Good signature from GPG...

**Comment by elliotkillick** [comment]
Whoops, looks like I forgot to escape the quotes in that last commit. Just fixed in 0af60f225b3e84a2041b27ce4bf7c181423dc142. Please reattempt.

**Comment by e6lk7dqzm83p** [comment]
Huzzah, I got it to work.  I appears that I in fact had a fedora-29 template, upgrading it to fedora-30 solved the problem.

**Comment by elliotkillick** [comment]
Ahh, it all makes sense now. Prior to Fedora 30 the `gpg` command pointed to version 1 of GPG. This was the problem because my PGP key is one of the new ones utilizing ECC encryption instead of RSA encryption which only GPG 2 supports.
https://www.phoronix.com/scan.php?page=news_item&px=Fedora-30-Default-GnuPG-2
