### ISSUE TITLE
Broken urls in download-windows.sh

### ISSUE THREAD

**Issue by im7mortal** [elliotkillick/qvm-create-windows-qube#63]
Following urls now are broken. I checked that rest worked well.

```
win7x64-ultimate.iso 
https://download.microsoft.com/download/5/1/9/5195A765-3A41-4A72-87D8-200D897CBE21/7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_ULTIMATE_x64FRE_en-us.iso

win2008r2.iso
 https://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
```

**Comment by elliotkillick** [comment]
This is now fixed with the release of Mido (inspired by [Fido](https://github.com/pbatard/Fido) from the same dev that made Rufus on Windows)!

Microsoft has finally purged all copies of Windows 7 from their servers so we're pulling from web.archive.org now and making sure to verify checksums of course: https://github.com/pbatard/Fido/issues/64

Someone contributing to the Metasploitable project found another link to an identical Windows Server 2008 R2 so I simply updated that: https://github.com/rapid7/metasploitable3/pull/563
