### ISSUE TITLE
download-windows.sh problem with scurl_file; curl fails for majority of installations (fedora and debian)

### ISSUE THREAD

**Issue by im7mortal** [elliotkillick/qvm-create-windows-qube#64]
Some reason `curl --output "$out_file" --"tlsv$tls_version" --proto =https -- "$url"`  doesn't download iso for majority of installations. But **win81x64-enterprise-eval** and **win2012r2-eval** work well.
The wget works well with all installations. 

```
scurl_file() {
    out_file="$1"
    tls_version="$2"
    url="$3"

    # Map the TLS version to the corresponding `--secure-protocol` option in wget
    case "$tls_version" in
        1.2)
            secure_protocol="TLSv1_2"
            ;;
        1.3)
            secure_protocol="TLSv1_3"
            ;;
        *)
            echo -e "${RED}[!]${NC} Unsupported TLS version: $tls_version. Exiting..." >&2
            exit 1
            ;;
    esac

    until wget --output-document="$out_file" --secure-protocol="$secure_protocol" --https-only "$url"; do
        echo -e "${RED}[!]${NC} Failed to download Windows! Is there an Internet connection? Retrying in 10 seconds..." >&2
        sleep 10
    done
}
```

**Comment by elliotkillick** [comment]
This is due to `curl` missing `--location` now that Microsoft changed the location of all their download to Azure (but at least added HTTP redirects which `curl` is not configured to follow).

**Comment by elliotkillick** [comment]
This is now fixed with the release of Mido! Check it out: https://github.com/elliotkillick/qvm-create-windows-qube/blob/master/windows-media/isos/mido.sh

A big plus with it is that it always gets the most up-to-date link from the official Microsoft pages which means this problem should be solved for the foreseeable future (also, this makes maintenance doable).

Windows 11 (and Server 2022) download support is already in Mido so this will also help us add support for those newer OSs!
