### ISSUE TITLE
Simplify Windows ISO creation

### ISSUE THREAD

**Issue by doug1** [ElliotKillick/qvm-create-windows-qube#67]
It may be possible to generate the ISO image without copying all of the files to a temp directory.  The genisoimage command can take multiple dirs/files to overlay in the final image.

Try something like this:
```
genisoimage -udf -b boot.bin -no-emul-boot -allow-limited-size -quiet -o "$final_iso" "$iso_mntpoint" Autounattend.xml boot.bin 
```

**Comment by ElliotKillick** [comment]
Thanks for finding this, just wish someone suggested it to me earlier! It turns out you can also use `-graft-points` to set the destination filename different from the source filename which is exactly what we needed for this. I guess if I had read the `genisoimage` manual's description more thoroughly when I was first developing this script I would have found this out myself but I was in too much of a time crunch.

In any case, this should collectively save users a lot time in generating the initial Windows ISO (it's cached after first generation but still for new ISOs downloaded with Mido).
